name: Ansible Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Ansible Lint
        uses: ansible/ansible-lint-action@main
        with:
          targets: ""
          override-deps: |
            ansible-lint==5.3.2
          args: "-x git-latest,command-instead-of-shell"